---
- name: "NEXUS - CLEANING UP TACACS CONFIG EXCEPT NEW ISE SERVERS AND GROUPS"
  hosts: nexus
  become: yes
  become_method: enable
  gather_facts: false
  vars:
    username: 'user1'
    password: 'Ensono$123'

  tasks:
    - name: LOOKING FOR TACACS SERVER GROUPS
      cisco.nxos.nxos_command:
        commands:
          - show run tacacs
      register: var_result_1
    
    - name: "test"
      set_fact:
        var_Server_group: '{{ var_result_1.stdout | regex_findall("aaa group server tacacs. \w+") | regex_replace("aaa group server tacacs\+ ","") }}'


    - name: PARSING
      ansible.utils.cli_parse:
        command: show run tacacs
        parser:
          name: ansible.utils.textfsm
          template_path: "templates/nxos_show_tacacs_aaa_groups.textfsm"
        set_fact: var_aaa_tacacs_groups

    - debug:
        msg: "{{ var_aaa_tacacs_groups[0].AAA_GROUP_NAME }}"


    - name: REMOVING GROUPS
      cisco.nxos.nxos_config:
        lines:
          - "no aaa group server tacacs+ {{ item.AAA_GROUP_NAME }}"
      when: item.AAA_GROUP_NAME != "ISE "
      with_items: '{{ var_aaa_tacacs_groups }}'

    - name: REMOVING SERVERS with INCLUDED TASK
      include_tasks: nxos_remove_server.yml
      when: '{{ servers_list.AAA_GROUP_NAME != "ISE " }}'
      loop: "{{ var_aaa_tacacs_groups }}"
      loop_control:
        loop_var: servers_list



...
